fix(bin,devcontainer): use bash command group to apply variable in the outer environment

diff --git a/bin/setup-devcontainer b/bin/setup-devcontainer
--- a/bin/setup-devcontainer
+++ b/bin/setup-devcontainer
@@ -25,7 +25,7 @@ if ! ansible_locale="$(get_valid_utf8_locale)"; then
 elif [ "${ansible_locale:-}" != "en_US.UTF-8" ] && ! locale_exists "en_US.UTF-8"; then
   # VSCode sets LANG to en_US.UTF-8 if LANG isn't set in advanced
   # regardless of locally available locales
-  (generate_en_us_utf8_locale && ansible_locale="en_US.UTF-8") || echo "Warning: Failed to generate en_US.UTF-8 locale, terminals in VS Code may display incorrectly."
+  { generate_en_us_utf8_locale && ansible_locale="en_US.UTF-8"; } || echo "Warning: Failed to generate en_US.UTF-8 locale, terminals in VS Code may display incorrectly."
 fi
 
 echo "==> Running devcontainer profile ..."
